import React from 'react';
import ConfidenceGauge from './ConfidenceGauge';
import ConsistencyChart from './ConsistencyChart';
import AccuracyTrendsChart from './AccuracyTrendsChart';
import StressTimeline from './StressTimeline';
import Recommendations from './Recommendations';
import { Activity } from 'lucide-react';

export default function AnalyticsView({ metrics, onConfidenceChange }) {
  if (!metrics) {
    return (
      <div className="flex flex-col items-center justify-center py-20 text-slate-400">
        <Activity className="w-12 h-12 text-purple-500 animate-pulse mb-3" />
        <p className="text-sm font-medium">No telemetry stats available to display. Log study sessions first.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6">
      
      {/* Title */}
      <div>
        <h2 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-indigo-400">
          Telemetry & AI Diagnostics
        </h2>
        <p className="text-xs text-slate-400 mt-1">Real-time performance analytics generated by the adaptive AI routine models</p>
      </div>

      {/* Recommendations Banner */}
      <Recommendations alerts={metrics?.alerts} />

      {/* Charts Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <ConfidenceGauge exams={metrics?.exams} onConfidenceChange={onConfidenceChange} />
        
        <ConsistencyChart
          weeklyHours={metrics?.weekly_hours}
          consistencyScore={metrics?.consistency_score}
          averageHours={metrics?.average_hours_per_day}
        />
        
        <AccuracyTrendsChart accuracyTrends={metrics?.subject_accuracy_trends} />
        
        <div className="lg:col-span-3">
          <StressTimeline stressScores={metrics?.stress_scores} stressDates={metrics?.stress_dates} />
        </div>
      </div>

    </div>
  );
}
